name: Unit tests
on: [push]

jobs:
  run_unit_tests_job:
    runs-on: ubuntu-latest
    name: Run unit tests

    strategy:
      matrix:
        python-version: ["3.8"]
        pytorch-version: ["torch==1.6.0", "torch"]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy ${{matrix.pytorch-version}} --no-cache-dir

      - name: Prepare repo
        uses: actions/checkout@master

      - name: Run unit tests.
        run: |
          python -m unittest